# Generated by Django 5.2.3 on 2025-08-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['updated_at']},
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='New Chat', max_length=100),
        ),
        migrations.AddField(
            model_name='summary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
