# Generated by Django 5.2.3 on 2025-08-28 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_conversation_options_conversation_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['updated_at']},
        ),
    ]
